### ISSUE TITLE
HolyHammer doesn't work for me

### ISSUE THREAD

**Issue by SOwens** [HOL-Theorem-Prover/HOL#280]
I tried to use HolyHammer according to the suggestion in its README in src/holyhammer, but get an error as follows. I'm on the latest version of OS X, and an up-to-date version of the master branch.

---------------------------------------------------------------------
       HOL-4 [Kananaskis 10 (stdknl, built Sat Aug 22 11:12:07 2015)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------

[Use-ing configuration file /Users/sao/.hol-config.sml]
Poly/ML 5.5.2 Release
>   load "holyHammer";
  open holyHammer;
  hh [] ``1 + 1 = 2``;
val it = (): unit
> datatype ATP = Eprover | Vampire | Z3
datatype PREDICTOR = Geo | KNN | Mepo | NBayes
val atp_settings = fn: ATP -> PREDICTOR * int * int
val hh = fn: thm list -> term -> unit
val hh_atp = fn: ATP -> thm list -> term -> unit
val hh_goal = fn: thm list -> term list * term -> unit
val reset_hh = fn: unit -> unit
val set_minimization = fn: bool -> unit
val set_prediction = fn: ATP -> int -> unit
val set_predictor = fn: ATP -> PREDICTOR -> unit
val set_predictors = fn: PREDICTOR -> unit
val set_timeout = fn: int -> unit
> eprover.sh: line 12: timeout: command not found
Exception- Status "Unknown" raised
>

**Comment by xrchz** [comment]
At a glance, it looks like the `timeout` command is missing on your system. This command is available as part of GNU coreutils, so you could try installing it. Currently it would seem that HolyHammer depends on `timeout`. Perhaps @barakeel knows a way to avoid that dependency.

**Comment by SOwens** [comment]
After installing timeout, I get the following. This is with a symlink to eprover in the HOL/src/holyhammer/provers/eprover. I also have a symlink to z3 in that directory too.

> hh [] ``1 + 1 = 2``;
eprover: Warning: Cannot set stack limit:
eprover: Warning: Undefined error: 0
eprover: Warning: Continuing with default stack limit
Exception- Status "Unknown" raised
> eprover: CPU time limit exceeded, terminating
eprover: CPU time limit exceeded, terminating
eprover: CPU time limit exceeded, terminating

**Comment by xrchz** [comment]
I tried it myself, using just a symlink to `eprover` at `src/holyhammer/provers/eprover/eprover`, and found that I get `Exception- Status "Unknown" raised` if I run `hh [] 1+1=2`. (By the way, your symlink to `z3` should be in the `z3` directory, not `eprover`.)

However, if I step through the definition of `hh` manually, I get the correct result of some lemmas found by the prover.

The problem for me appears to be that `reconstructl` is called too quickly, before the prover has a chance to write its status file. I think there is some synchronisation missing: there should be a wait loop or something to know that the provers have finished (or reached the timeout).

**Comment by xrchz** [comment]
Another minor problem: the `README` suggests that `eprover` and `z3` are provided by default, but I don't think that is the case. If they are indeed not bundled with HOL, I suggest the `README` be updated to reflect that, and perhaps also include some suggestions to install them.

**Comment by barakeel** [comment]
I hope I fixed your issues:
   I remove dependencies to timeout as the provers already have their internal timeout. I provided adresses for z3 and eprover where the binaries can be fetched.  
  The need for symlink was removed but binary now need to be in the $PATH variable so that they can be called from the command line.
  I updated the .gitignore file accordingly.

All the best,

Thibault

**Comment by barakeel** [comment]
To Ramana: I thought the sml command OS.Process.system would wait for the called of the external process to finish. You could try to use set_timeout 15 and try to call hh [] ``1 = 2`` to see if the call really lasts for 15 seconds. I do not have this issue on my computer.

Thibault

**Comment by xrchz** [comment]
I'm afraid I still have the problem of `Status "Unknown"` if I run `hh` (but it works if I step through it manually). `set_timeout 15` does not make the call last for 15 seconds, but I believe this is correct behaviour, since the timeout is a time _limit_, and the prover call probably doesn't need that long on my conjecture.

Looking at `hh.sh`, I think I see why there is a problem. You run `eprover` and `vampire` in the background (i.e., in parallel) and only wait for `z3`. But I do not have `z3` installed (I only have `eprover`). So, `hh.sh` will exit almost immediately even while `eprover` is still running. I think `hh.sh` really needs to wait until all the provers have finished (or timed out) before it exits.

**Comment by barakeel** [comment]
Thank you, I can reproduce the error and adding "& wait" fixed it. I hope it will work now.

Thibault

**Comment by xrchz** [comment]
Thanks @barakeel! It works for me now. I leave it to @SOwens to re-open if he still has problems.

**Comment by SOwens** [comment]
Now when I try it with both z3 and eprover it goes away for 2or 3 seconds and then comes back with:

Exception- Status " ResourceOut" raised

**Comment by xrchz** [comment]
Which conjecture are you trying to prove? You may need to use `set_timeout` and give it a higher timeout to find the proof.

**Comment by SOwens** [comment]
Still on 1 + 1 = 2.

-Scott

**Comment by xrchz** [comment]
It works for me, so I'm not sure. My suggestions for debugging this:
* try a higher time limit
* watch the resource usage of the provers with `top` or equivalent
* ensure you're at type `:num` (actually, I just checked it works for `:int` too)
* step through the definition of `hh` manually to see where the exception comes from

**Comment by barakeel** [comment]
- Are you sure about the exception?
     Exception- Status " Theorem" raised
- This is the only string the function {reconstructl} should not be able to raise.
- Could you try to pull one more time and rebuild holyhammer by typing Holmake clean and Holmake in the five directories listed in the README?

**Comment by SOwens** [comment]
I did a git pull in HOL, and a git clean -xdf in the holyhammer directory, and then built HOL. I tried the Holmakes from the readme, but they didn't do anything. I think building the HOL system builds everything). 

dhcp297B:HOL sao$ z3 --version
Z3 version 4.4.0

dhcp297B:HOL sao$ eprover --version
eprover: Warning: Cannot set stack limit:
eprover: Warning: Undefined error: 0
eprover: Warning: Continuing with default stack limit
E 1.8-001 Gopaldhara

I get the results below:

---------------------------------------------------------------------
       HOL-4 [Kananaskis 10 (stdknl, built Mon Aug 24 11:06:47 2015)]

       For introductory HOL help, type: help "hol";
       To exit type <Control>-D
---------------------------------------------------------------------

[Use-ing configuration file /Users/sao/.hol-config.sml]
Poly/ML 5.5.2 Release
>   load "holyHammer";
val it = (): unit
>   open holyHammer;
datatype ATP = Eprover | Vampire | Z3
datatype PREDICTOR = Geo | KNN | Kepo | Mepo | NBayes
val atp_settings = fn: ATP -> PREDICTOR * int * int
val hh = fn: thm list -> term -> unit
val hh_atp = fn: ATP -> thm list -> term -> unit
val hh_goal = fn: thm list -> term list * term -> unit
val hh_try = fn: thm list -> term -> unit
val reset_hh = fn: unit -> unit
val set_minimization = fn: bool -> unit
val set_prediction = fn: ATP -> int -> unit
val set_predictor = fn: ATP -> PREDICTOR -> unit
val set_predictors = fn: PREDICTOR -> unit
val set_timeout = fn: int -> unit
>   hh [] ``1 + 1 = 2``;
Exception- Status " ResourceOut" raised
> set_timeout 1000;
val it = (): unit
> hh [] ``1 + 1 = 2``;
Exception- Status " Theorem" raised
>

**Comment by xrchz** [comment]
I have
```
% eprover --version
E 1.9 Sourenee
```
in case it makes a difference.

**Comment by barakeel** [comment]
The second error is weird, but the first error tells me that I do not support at least one of your prover.
Can you see if the provers are parsed correclty in provers/eprover/eprover_out and in provers/z3/z3_out. These files contains a list of theorems.

**Comment by SOwens** [comment]
dhcp297B:provers sao$ cat eprover/eprover_out 
'thm/arithmetic/ALT_ZERO'
'thm/numeral/numeral_suc'
conjecture
'thm/arithmetic/NUMERAL_DEF'
'thm/arithmetic/ADD1'
'thm/arithmetic/TWO'
dhcp297B:provers sao$ cat z3/z3_out 
dhcp297B:provers sao$

**Comment by barakeel** [comment]
It seems that z3 is not finding a proof although it should I don't think it comes from the prover because I also tested with version 4.4.0 and it works fine for me. I would be interested in the result of 
"hh_atp Eprover [] ``1+1=2``;". I would expect the same error Status "Theorem" raised.

**Comment by barakeel** [comment]
It actually fails for z3 version 4.4.0. I am trying to fix it , you can still fetch the 4.0 version from the adress proposed by the Readme.

**Comment by barakeel** [comment]
Maybe I should revert to the binary (symlink) method where you fetch a fixed version, because the options keep changing for the provers and sometimes features are removed.

**Comment by SOwens** [comment]
You're right about eprover. Vampire and Z3 both give Unknown even though z3 is in my path, and I haven't installed Vampire.

> set_timeout 1000;
val it = (): unit
> hh_atp Eprover [] ``1 + 1 = 2``;
Exception- Status " Theorem" raised
> hh_atp Vampire [] ``1 + 1 = 2``;
Exception- Status "Unknown" raised
> hh_atp Z3 [] ``1 + 1 = 2``;
Exception- Status "Unknown" raised
>

**Comment by barakeel** [comment]
You may not need such a high time out unless, I am perfectly fine working with a time out of 5 seconds. You may need 10 if your computer is a bit slower. I fixed the first issue, mainly that the parsing of the status was leaving a blank space before "Theorem", so eprover should work fine. Concerning z3, it may be difficult to make it work with this version but I am still looking at it.

**Comment by SOwens** [comment]
The basic test seems to work for me now.

**Comment by barakeel** [comment]
I modified again the way provers are called, going back to the binary and symlink approach. Now provers' binaries should be copied to src/provers in the same directory. In that way, you can download the 4.0 version of z3 and put it in this directory without downgrading your current z3. The 4.4 version of z3 does not support tptp input in its options, so I will not be able to support it before we have translation to SMT-lib, which could be a while.
